/**
 * The ODD ALL-HALF hypergeometric tower — a family indexed by a single integer.
 *
 *   Γ_d = ⟨ Comp((x−1)^d), Comp((x+1)^d) ⟩,   d ≥ 5 odd
 *
 * ("Odd All-Half Thinness": after a rational Levelt change of basis Γ_d is
 * generated by a regular unipotent A and a reflection R, and a positivity
 * theorem for an upper-Hessenberg walk determinant certifies ℙΓ_d ≅ (ℤ/2) ∗ ℤ,
 * Zariski dense in an orthogonal group and of infinite index in it.)
 *
 * This module is the family's DATA + the thin recipe, in the sense of the other
 * `examples/` catalogs — except that where those transcribe a finite table, this
 * one is GENERATED from d. There is no catalog file to edit; `EXAMPLES` is a
 * function of `DEGREES`.
 *
 * HOW THE GENERATORS ARE BUILT ("route B"). The coefficients of (x∓1)^d are
 * binomial coefficients, so both polynomials are written down directly as exact
 * integer lists and handed to `companion`. The hypergeometric catalogs reach the
 * same matrices the long way round — via rotation numbers, `cyclotomicProduct`
 * multiplies out ∏(x − e^{2πiαⱼ}) in floating point and snaps to integers — and
 * for THIS family that route is available too, since α is d copies of 0 and β is
 * d copies of ½. The two must agree exactly; `scripts/tests/all-half-odd-gates.ts`
 * checks that they do, which makes the older path a free cross-check rather than
 * a dependency. Nothing here touches floating point until `companion` packs the
 * integers into a Float64Array.
 *
 * THE ALPHABET is the shared `companionPairAlphabet(A, B, 'free-product')`: it
 * forms T = B·A⁻¹ and certifies T² = I. That T is exactly the paper's reflection
 * R (the paper sets B = RA, so R = BA⁻¹), and since A ∈ SL_d(ℤ) the inverse is
 * integral and T² = I holds on the nose, not to a tolerance. Walking {T, B, B⁻¹}
 * rather than {A, A⁻¹, B, B⁻¹} is the point: with T an involution the
 * non-backtracking tree enumerates exactly the alternating words T B^{k₁} T B^{k₂}⋯,
 * which is the normal form of ⟨T⟩ ∗ ⟨B⟩ — one node per group element, and a 2^N
 * tree instead of 3^N.
 *
 * SEEDING IS BY AN EXPLICIT WORD, deliberately. Both generators are unipotent
 * (χ_A = (x−1)^d, χ_B = (x+1)^d), so every characteristic root is a d-fold root
 * at ±1, and numeric root-finding scatters an m-fold root by ~ε^(1/m): the
 * spurious |λ| reported for the *unipotent* B climbs from 1.0006 at d=5 to 3.44
 * at d=15, far above any usable `expand` floor. `seedFromLoxodromic` would
 * therefore certify a parabolic as loxodromic somewhere up the tower. The fixed
 * word γ = B²T sidesteps the search entirely: it is proximal at every d tested
 * (|λ| growing 39.9 → 364 over d = 5…15) and power-iterates to drift ≤ 1e-16.
 * The gates certify it is not unipotent by an exact integer trace test.
 */

import { type Mat, companion } from '../../core/matrix.ts';
import { makeMatrixAction } from '../../core/matrixAction.ts';
import { binomialRow } from './all-half-kernel.ts';
import { companionPairAlphabet, WALK_LABELS, type Walk } from './recipe.ts';
import type { GroupAction } from '../../core/group.ts';
import { seedFromWord, type Seed } from '../../core/seed.ts';

/** This family's generating set: {T, B} with T = B·A⁻¹ the paper's reflection. */
export const ALL_HALF_ODD_WALK: Walk = 'free-product';

/** Generator labels in code order, for `formatWord` and the palettes. */
export const ALL_HALF_ODD_LABELS = WALK_LABELS[ALL_HALF_ODD_WALK];

/**
 * Seed word in APPLY ORDER (see the convention in core/group.ts): apply T, then
 * B, then B. As a group element that is the reversed product B·B·T = B²T.
 */
export const ALL_HALF_ODD_SEED_WORD: readonly number[] = [0, 1, 1];

/** Degrees offered by the family. Odd and ≥ 5, as the theorem requires; the
 *  upper end is where the binomial coefficients still sit comfortably inside
 *  exact float64 integers. */
export const DEGREES: readonly number[] = [5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25];

/** Stable per-degree identifier. Saved view presets key off this string, so it
 *  must not change. `-odd-` leaves room for the even (symplectic) tower. */
export const exampleId = (d: number): string => `allhalf-odd-d${d}`;

export interface AllHalfOddExample {
  id: string;
  label: string;
  /** The degree; the group acts on RP^{d-1}. */
  d: number;
}

export const EXAMPLES: readonly AllHalfOddExample[] = DEGREES.map((d) => ({
  id: exampleId(d),
  label: `d = ${d}`,
  d,
}));

const byId = new Map(EXAMPLES.map((e) => [e.id, e]));

export function exampleFor(id: string): AllHalfOddExample {
  const e = byId.get(id);
  if (!e) throw new Error(`unknown all-half-odd id: ${id}`);
  return e;
}

// ─── The construction ────────────────────────────────────────────────────────

function assertOdd(d: number): void {
  if (!Number.isInteger(d) || d < 5 || d % 2 === 0) {
    throw new Error(`all-half-odd: d must be an odd integer ≥ 5 (got ${d})`);
  }
}

export { binomialRow };

/**
 * The two defining polynomials as high-degree-first monic integer coefficient
 * lists: f = (x−1)^d has coeff[i] = (−1)^i C(d,i), g = (x+1)^d has coeff[i] =
 * C(d,i).
 */
export function allHalfOddPolynomials(d: number): { f: number[]; g: number[] } {
  assertOdd(d);
  const c = binomialRow(d);
  return {
    f: c.map((v, i) => (i % 2 === 0 ? v : -v)),
    g: c.slice(),
  };
}

/** The generating pair A = Comp((x−1)^d), B = Comp((x+1)^d). */
export function allHalfOddMatrices(d: number): { A: Mat; B: Mat } {
  const { f, g } = allHalfOddPolynomials(d);
  return { A: companion(f), B: companion(g) };
}

/** The GroupAction on RP^{d-1}, over the {T, B, B⁻¹} free-product alphabet. */
export function allHalfOddAction(d: number): GroupAction {
  const { A, B } = allHalfOddMatrices(d);
  return makeMatrixAction(companionPairAlphabet(A, B, ALL_HALF_ODD_WALK));
}

/**
 * Basepoint on the limit set: the attracting fixed point of γ = B²T, reached by
 * power iteration. Explicit rather than searched — see the note at the top of
 * this file on why the loxodromic search is unsafe for this family.
 */
export function seedAllHalfOdd(action: GroupAction, iters = 400): Seed {
  return seedFromWord(action, ALL_HALF_ODD_SEED_WORD, {
    iters,
    labels: ALL_HALF_ODD_LABELS,
  });
}

/**
 * The rotation tuples (α, β) that describe this group in the language of the
 * hypergeometric catalogs: α is d copies of 0, β is d copies of ½. Provided so
 * the older `cyclotomicProduct` route can be run against the binomial route as a
 * cross-check; the construction above does not use it.
 */
export function allHalfOddRotations(d: number): { alpha: string[]; beta: string[] } {
  assertOdd(d);
  return {
    alpha: Array.from({ length: d }, () => '0'),
    beta: Array.from({ length: d }, () => '1/2'),
  };
}
