/**
 * The full Bajpai–Singh degree-5 orthogonal hypergeometric atlas — all 77
 * monodromy groups, the data behind the o5-explorer demo.
 *
 * GENERATED by scripts/gen-o5-catalog.ts from orthogonal_hypergeometric_group_
 * tables.csv (a transcription of arXiv:1706.08791, Tables 1–7), cross-validated
 * against a second independent transcription and against the Bajpai–Nitsche
 * O(5) paper. Edit the generator, not this file.
 *
 * Each group is a pair (α, β) of five rotation numbers; the generators are the
 * companion matrices of f = ∏(x − e^{2πiαⱼ}) and g = ∏(x − e^{2πiβⱼ}) — built
 * from (α, β) on demand by the hypergeometric recipe (./recipe.ts). This file
 * is pure data + the row→example derivation; no matrices are stored here.
 *
 *   No. 1–7    O(4,1) thin        (Fuchs–Meiri–Sarnak)
 *   No. 8–43   O(3,2) arithmetic  (Venkataramana / Singh / Bajpai–Singh)
 *   No. 44–47  O(5)   finite      (positive-definite form — no limit set)
 *   No. 48–67  O(3,2) thin / open / arithmetic
 *   No. 68–77  O(4,1) thin / open
 * The 28 thin + 8 open are the limit-set headliners; arithmetic groups are
 * lattices, so their orbit closure is the whole boundary (dense, not fractal).
 */

import type { Walk } from './recipe.ts';

export type O5FormType = 'O(3,2)' | 'O(4,1)' | 'O(5)';
export type O5Status = 'thin' | 'arithmetic' | 'open' | 'finite';

/** This atlas's natural generating set: the free product {T, B} with T = B·A⁻¹
 *  an involution (Bajpai–Nitsche "Thin Monodromy in O(5)", Thm 1). */
export const ORTHOGONAL_DEGREE5_WALK: Walk = 'free-product';

export interface OrthogonalRow {
  /** Bajpai–Singh global numbering, 1–77. */
  bsNo: number;
  /** Source table in arXiv:1706.08791 (1–7). */
  table: number;
  type: O5FormType;
  status: O5Status;
  source: string;
  alpha: readonly string[];
  beta: readonly string[];
  /** Label in Bajpai–Nitsche "Thin Monodromy in O(5)" (only the 29 groups that
   *  appear there). */
  bdn?: string;
}

export interface OrthogonalExample {
  id: string;
  label: string;
  bsNo: number;
  type: O5FormType;
  status: O5Status;
  source: string;
  bdnLabel?: string;
  /** True if B = companion(g) has infinite order (β has a repeated rotation). */
  bInfinite: boolean;
  alpha: readonly string[];
  beta: readonly string[];
}

export const ROWS: readonly OrthogonalRow[] = [
  { bsNo:  1, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo:  2, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']         },
  { bsNo:  3, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo:  4, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo:  5, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '1/3', '2/3', '1/6', '5/6']       , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']              },
  { bsNo:  6, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '1/10', '3/10', '7/10', '9/10']   , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']              },
  { bsNo:  7, table: 1, type: 'O(4,1)', status: 'thin'       , source: 'Fuchs–Meiri–Sarnak', alpha: ['0', '1/10', '3/10', '7/10', '9/10']   , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo:  8, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo:  9, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 10, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']              },
  { bsNo: 11, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/6', '1/6', '5/6', '5/6']              },
  { bsNo: 12, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 13, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']         },
  { bsNo: 14, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/3', '2/3', '1/4', '3/4']       , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']              },
  { bsNo: 15, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/5', '2/5', '3/5', '4/5']       , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 16, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/10', '3/10', '7/10', '9/10']   , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 17, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 18, table: 2, type: 'O(3,2)', status: 'arithmetic' , source: 'Venkataramana', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 19, table: 3, type: 'O(3,2)', status: 'arithmetic' , source: 'Singh', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 20, table: 3, type: 'O(3,2)', status: 'arithmetic' , source: 'Singh', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/6', '1/6', '5/6', '5/6']              },
  { bsNo: 21, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 22, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/4', '3/4', '1/6', '5/6']              },
  { bsNo: 23, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/6', '1/6', '5/6', '5/6']              },
  { bsNo: 24, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/6', '1/6', '5/6', '5/6']              },
  { bsNo: 25, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 26, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/4', '3/4', '1/6', '5/6']              },
  { bsNo: 27, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '1/3', '2/3', '2/3']       , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo: 28, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '2/3', '1/4', '3/4']       , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo: 29, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '2/3', '1/4', '3/4']       , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']         },
  { bsNo: 30, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '2/3', '1/6', '5/6']       , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 31, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '2/3', '1/6', '5/6']       , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo: 32, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/3', '2/3', '1/6', '5/6']       , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']         },
  { bsNo: 33, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/5', '2/5', '3/5', '4/5']       , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']              },
  { bsNo: 34, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/5', '2/5', '3/5', '4/5']       , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']              },
  { bsNo: 35, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/6', '1/6', '5/6', '5/6']       , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']              },
  { bsNo: 36, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/6', '1/6', '5/6', '5/6']       , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']              },
  { bsNo: 37, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/6', '1/6', '5/6', '5/6']       , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 38, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/8', '3/8', '5/8', '7/8']       , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']              },
  { bsNo: 39, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/8', '3/8', '5/8', '7/8']       , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']              },
  { bsNo: 40, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/8', '3/8', '5/8', '7/8']       , beta: ['1/2', '1/4', '1/4', '3/4', '3/4']              },
  { bsNo: 41, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']              },
  { bsNo: 42, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']              },
  { bsNo: 43, table: 4, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']              },
  { bsNo: 44, table: 5, type: 'O(5)', status: 'finite'     , source: '—', alpha: ['0', '1/3', '2/3', '1/4', '3/4']       , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 45, table: 5, type: 'O(5)', status: 'finite'     , source: '—', alpha: ['0', '1/3', '2/3', '1/6', '5/6']       , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 46, table: 5, type: 'O(5)', status: 'finite'     , source: '—', alpha: ['0', '1/5', '2/5', '3/5', '4/5']       , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 47, table: 5, type: 'O(5)', status: 'finite'     , source: '—', alpha: ['0', '1/8', '3/8', '5/8', '7/8']       , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']          },
  { bsNo: 48, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/2', '1/2', '1/2', '1/2']             , bdn: 'O(3,2) Case 1' },
  { bsNo: 49, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/2', '1/2', '1/3', '2/3']             , bdn: 'O(3,2) Case 2' },
  { bsNo: 50, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/2', '1/2', '1/4', '3/4']             , bdn: 'O(3,2) Case 3' },
  { bsNo: 51, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/2', '1/2', '1/6', '5/6']             , bdn: 'O(3,2) Case 4' },
  { bsNo: 52, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']             , bdn: 'O(3,2) open 1' },
  { bsNo: 53, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']             , bdn: 'O(3,2) open 2' },
  { bsNo: 54, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/3', '2/3', '1/6', '5/6']             , bdn: 'O(3,2) Case 5' },
  { bsNo: 55, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/4', '3/4', '1/6', '5/6']             , bdn: 'O(3,2) open 3' },
  { bsNo: 56, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']             , bdn: 'O(3,2) Case 6' },
  { bsNo: 57, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']             , bdn: 'O(3,2) Case 7' },
  { bsNo: 58, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/10', '3/10', '7/10', '9/10']         , bdn: 'O(3,2) Case 8' },
  { bsNo: 59, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '0', '0']               , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']        , bdn: 'O(3,2) Case 9' },
  { bsNo: 60, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/2', '1/2', '1/3', '2/3']             , bdn: 'O(3,2) Case 10' },
  { bsNo: 61, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']             , bdn: 'O(3,2) open 4' },
  { bsNo: 62, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/2', '1/2', '1/3', '2/3']             , bdn: 'O(3,2) Case 11' },
  { bsNo: 63, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']             , bdn: 'O(3,2) open 5' },
  { bsNo: 64, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/3', '2/3', '1/4', '3/4']             , bdn: 'O(3,2) open 6' },
  { bsNo: 65, table: 6, type: 'O(3,2)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']             , bdn: 'O(3,2) Case 12' },
  { bsNo: 66, table: 6, type: 'O(3,2)', status: 'open'       , source: '—', alpha: ['0', '1/10', '3/10', '7/10', '9/10']   , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']             , bdn: 'O(3,2) open 7' },
  { bsNo: 67, table: 6, type: 'O(3,2)', status: 'arithmetic' , source: 'Bajpai–Singh–Singh', alpha: ['0', '1/12', '5/12', '7/12', '11/12']  , beta: ['1/2', '1/3', '1/3', '2/3', '2/3']              },
  { bsNo: 68, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/2', '1/2', '1/4', '3/4']             , bdn: 'O(4,1) Case 1' },
  { bsNo: 69, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/2', '1/2', '1/6', '5/6']             , bdn: 'O(4,1) Case 2' },
  { bsNo: 70, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/3', '2/3']           , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']             , bdn: 'O(4,1) Case 3' },
  { bsNo: 71, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/3', '2/3', '1/6', '5/6']             , bdn: 'O(4,1) Case 4' },
  { bsNo: 72, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']             , bdn: 'O(4,1) Case 5' },
  { bsNo: 73, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']             , bdn: 'O(4,1) Case 6' },
  { bsNo: 74, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/4', '3/4']           , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']        , bdn: 'O(4,1) Case 7' },
  { bsNo: 75, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/8', '3/8', '5/8', '7/8']             , bdn: 'O(4,1) Case 8' },
  { bsNo: 76, table: 7, type: 'O(4,1)', status: 'thin'       , source: 'Bajpai–Nitsche (this O(5) paper)', alpha: ['0', '0', '0', '1/6', '5/6']           , beta: ['1/2', '1/12', '5/12', '7/12', '11/12']        , bdn: 'O(4,1) Case 9' },
  { bsNo: 77, table: 7, type: 'O(4,1)', status: 'open'       , source: '—', alpha: ['0', '1/10', '3/10', '7/10', '9/10']   , beta: ['1/2', '1/5', '2/5', '3/5', '4/5']             , bdn: 'O(4,1) open 1' },
];

// ─── Row → OrthogonalExample ────────────────────────────────────────────────

function gcd(a: number, b: number): number { return b === 0 ? a : gcd(b, a % b); }

/** A rotation reduced to lowest terms mod 1, as a canonical "num/den" string. */
function reduceRotation(s: string): string {
  const t = s.trim();
  const slash = t.indexOf('/');
  if (slash === -1) return '0';
  const p = parseInt(t.slice(0, slash), 10);
  const q = parseInt(t.slice(slash + 1), 10);
  const num = ((p % q) + q) % q;
  if (num === 0) return '0';
  const g = gcd(num, q) || 1;
  return `${num / g}/${q / g}`;
}

/** B = companion(g) has infinite order ⟺ g has a repeated root ⟺ β has a
 *  repeated rotation. */
function betaInfiniteOrder(beta: readonly string[]): boolean {
  const reduced = beta.map(reduceRotation);
  return new Set(reduced).size < reduced.length;
}

export function rowToExample(row: OrthogonalRow): OrthogonalExample {
  return {
    id: `g${row.bsNo}`,
    label: `№${row.bsNo}`,
    bsNo: row.bsNo,
    type: row.type,
    status: row.status,
    source: row.source,
    bdnLabel: row.bdn,
    bInfinite: betaInfiniteOrder(row.beta),
    alpha: row.alpha,
    beta: row.beta,
  };
}

/** The full atlas as ready-to-use examples (Bajpai–Singh order, No. 1–77). */
export const CATALOG_EXAMPLES: readonly OrthogonalExample[] = ROWS.map(rowToExample);
