/**
 * Recipes for SU(2,1) acting on CH² — data → GroupAction.
 *
 * The central construction (the one the Goldman–Parker ideal triangle groups
 * are built from): three points p₁, p₂, p₃ on ∂CH² determine three complex
 * geodesics (pairwise), and the group is generated by the three COMPLEX
 * REFLECTIONS ι_k = R_{−1} in those lines (see `complexReflection`, which also
 * provides the order-p phases ζ = e^{2πi/p} for Mostow-type groups and point
 * rotations for negative mirror vectors). Each ι_k is an involution. Walking the
 * three involutions gives reduced words of the (∞, ∞, ∞) triangle group. The
 * one-real-parameter family of ideal triples is classified by the Cartan
 * angular invariant A ∈ (−π/2, π/2); `idealTrianglePoints(A)` produces a
 * normalized triple, so a Goldman–Parker catalog row is just a value of A
 * (or three explicit boundary points).
 *
 * Side products ιᵢιⱼ are PARABOLIC (they fix the shared ideal vertex), so the
 * loxodromic seed search skips past length-2 words automatically.
 */

import type { GroupAction } from '../../core/group.ts';
import type { CMat, Cx } from '../../core/complexMatrix.ts';
import {
  type CGen, asComplexInvolutions, complexGeneratingSet, makeComplexMatrixAction,
} from '../../core/complexMatrixAction.ts';
import { seedFromLoxodromic, makeComplexDominantCriterion, type Seed } from '../../core/seed.ts';
import { type CVec3, cvec3, herm, polarVector } from './hermitian.ts';

/** ζ = e^{2πi/p}, the rotation phase of an order-p complex reflection. */
export function zetaOfOrder(p: number): Cx {
  return [Math.cos((2 * Math.PI) / p), Math.sin((2 * Math.PI) / p)];
}

/**
 * THE complex reflection formula: mirror polar to c, rotation phase ζ (|ζ|=1),
 *   R_ζ(z) = z + (ζ − 1)(⟨z, c⟩/⟨c, c⟩)c,
 * i.e. R_ζ fixes the mirror c^⊥ pointwise and multiplies c by ζ.
 *
 *   - POSITIVE c: the order-p complex reflection in the complex line c^⊥ when
 *     ζ = e^{2πi/p} — Goldman–Parker at the default ζ = −1 (an involution),
 *     Mostow's lattice generators at p ≥ 3 (NOT involutions: R_ζ⁻¹ = R_ζ̄, so
 *     walk them via `complexGeneratingSet` with involution unset).
 *   - NEGATIVE c: the elliptic rotation by ζ about the point [c] ∈ CH² — the
 *     same formula covers both ingredient types.
 *
 * det R_ζ = ζ has unit modulus, so R_ζ ∈ U(2,1); the projective action (all
 * the engine sees) is indifferent to the determinant. (The earlier
 * involution-only version of this function was the scalar multiple −R_{−1};
 * projectively identical, and the su21 gates pin the limit sets unchanged.)
 */
export function complexReflection(c: CVec3, zeta: Cx = [-1, 0]): CMat {
  const [cc] = herm(c, c);
  if (Math.abs(cc) < 1e-14) {
    throw new Error(`complexReflection: mirror vector must be non-null (⟨c,c⟩ = ${cc})`);
  }
  const sr = (zeta[0] - 1) / cc, si = zeta[1] / cc;  // s = (ζ−1)/⟨c,c⟩
  const J = [1, 1, -1] as const;
  const M = new Float64Array(18);
  for (let r = 0; r < 3; r++) {
    const cr = c[2 * r], ci = c[2 * r + 1];
    for (let k = 0; k < 3; k++) {
      const br = J[k] * c[2 * k], bi = -J[k] * c[2 * k + 1];  // J_k c̄_k
      const outR = cr * br - ci * bi, outI = cr * bi + ci * br;  // (c ⊗ Jc̄)_rk
      M[2 * (r * 3 + k)]     = (r === k ? 1 : 0) + sr * outR - si * outI;
      M[2 * (r * 3 + k) + 1] = sr * outI + si * outR;
    }
  }
  return M;
}

/** The three reflections of the ideal triangle on (p₁, p₂, p₃): ι_k fixes the
 *  complex line through the two points OTHER than p_k. */
export function idealTriangleReflections(
  p1: CVec3, p2: CVec3, p3: CVec3,
): [CMat, CMat, CMat] {
  return [
    complexReflection(polarVector(p2, p3)),
    complexReflection(polarVector(p3, p1)),
    complexReflection(polarVector(p1, p2)),
  ];
}

/** GroupAction of the ideal triangle group ⟨ι₁, ι₂, ι₃⟩ on the given triple. */
export function idealTriangleAction(p1: CVec3, p2: CVec3, p3: CVec3): GroupAction {
  return makeComplexMatrixAction(asComplexInvolutions(idealTriangleReflections(p1, p2, p3)));
}

/**
 * A normalized null triple with Cartan angular invariant A ∈ (−π/2, π/2):
 *   p₁ = (1, 0, 1),  p₂ = (−1, 0, 1),  p₃ = (−i·tan(A/2), √(1 − tan²(A/2)), 1).
 * At A = 0 this is the real triple (R-Fuchsian, limit set an R-circle); as
 * |A| → π/2 the triple degenerates onto a complex line. Round-trips through
 * `cartanInvariant` exactly (pinned by scripts/tests/su21-gates.ts).
 */
export function idealTrianglePoints(A: number): [CVec3, CVec3, CVec3] {
  if (!(Math.abs(A) < Math.PI / 2)) {
    throw new Error(`idealTrianglePoints: need |A| < π/2, got ${A}`);
  }
  const t = Math.tan(A / 2);
  const b = Math.sqrt(1 - t * t);
  return [
    cvec3([1, 0], [0, 0], [1, 0]),
    cvec3([-1, 0], [0, 0], [1, 0]),
    cvec3([0, -t], [b, 0], [1, 0]),
  ];
}

/** GroupAction from an explicit SU(2,1) generating set (mixed involution/free
 *  alphabet), for examples not of ideal-triangle form. */
export function su21Action(gens: readonly CGen[]): GroupAction {
  return makeComplexMatrixAction(complexGeneratingSet(gens));
}

const INVOLUTION_LABELS = ['ι₁', 'ι₂', 'ι₃', 'ι₄', 'ι₅'];

/** Complex dominant criterion with the expansion floor raised above the
 *  numeric-root scatter of a realified 6×6 parabolic (a 6-fold unit root
 *  scatters by ~ε^(1/6) ≈ 3e-3; the sl2c default floor of 1.001 would let
 *  parabolics like ιᵢιⱼ masquerade as loxodromic). */
const su21Criterion = makeComplexDominantCriterion({ expand: 1.02 });

/** Limit-set basepoint for an SU(2,1) group: attracting fixed point of the
 *  shortest certified loxodromic word. Uses the COMPLEX dominant criterion —
 *  the realified spectrum of a loxodromic carries a conjugate pair (or doubled
 *  real eigenvalue) at the top. Power iteration converges projectively; both
 *  boundary embeddings are phase-invariant. */
export function seedCH2(action: GroupAction, labels?: readonly string[]): Seed {
  return seedFromLoxodromic(action, {
    criterion: su21Criterion,
    labels: labels ?? INVOLUTION_LABELS.slice(0, action.numGenerators),
  });
}
