/**
 * Ideal tetrahedra on ∂CH² — the 4-point research family.
 *
 * Four ideal points p₁…p₄ span C(4,2) = 6 complex geodesics (the EDGES);
 * the tetrahedron group is generated by the 6 complex reflections ι_{ij} in
 * them. Each FACE (triple of points, omitting one) generates the Goldman–
 * Parker ideal triangle group ⟨ι_{jk}, ι_{ik}, ι_{ij}⟩ with parameter
 * A(pᵢ,pⱼ,pₖ) — so `cartanReport` is a genuine subgroup-discreteness filter
 * here (each face is a discrete embedding iff |A_face| ≤ A*, by Schwartz).
 * Discreteness of the WHOLE group is more than its faces: elements mixing
 * opposite edges (e.g. ι₁₂ι₃₄) are invisible to the face filter — classify
 * them with diagnostics.ts.
 *
 * The ideal quadrilateral group (reflections in the 4 cyclic SIDES only) is
 * the sub-alphabet CYCLIC_SIDES of the same construction — same points, same
 * mirrors, drop the two diagonals.
 *
 * Moduli: 4 points × 3 dof − dim PU(2,1) = 4. Parameterization used here:
 * the base face p₁p₂p₃ from `idealTrianglePoints(A)` (1 modulus) and p₄ in
 * Heisenberg coordinates (ζ, v) via `boundaryFromHeisenberg` (3 moduli) —
 * every Heisenberg point lifts to a null vector, so the parameterization can
 * never fall off the boundary.
 */

import type { GroupAction } from '../../core/group.ts';
import { type CMat, type Cx, cmatVec } from '../../core/complexMatrix.ts';
import { asComplexInvolutions, makeComplexMatrixAction } from '../../core/complexMatrixAction.ts';
import type { Seed } from '../../core/seed.ts';
import { type CVec3, CAYLEY, polarVector } from './hermitian.ts';
import { idealTrianglePoints, complexReflection, seedCH2 } from './recipe.ts';

export type IdealTetrahedron = readonly [CVec3, CVec3, CVec3, CVec3];

/** Edge order = generator-code order. Point indices are 0-based; the labels
 *  below are the 1-based names used everywhere user-facing. */
export const TETRA_EDGES: readonly (readonly [number, number])[] = [
  [0, 1], [0, 2], [0, 3], [1, 2], [1, 3], [2, 3],
];
export const TETRA_EDGE_LABELS: readonly string[] = ['ι₁₂', 'ι₁₃', 'ι₁₄', 'ι₂₃', 'ι₂₄', 'ι₃₄'];

/** Face k omits point k; entries are point indices of the face triple. */
export const TETRA_FACES: readonly (readonly [number, number, number])[] = [
  [1, 2, 3], [0, 2, 3], [0, 1, 3], [0, 1, 2],
];

/** Generator codes (into TETRA_EDGES order) of the 4 cyclic sides
 *  p₁p₂, p₂p₃, p₃p₄, p₄p₁ — the ideal QUADRILATERAL sub-alphabet. */
export const CYCLIC_SIDES: readonly number[] = [0, 3, 5, 2];

/** The 6 edge polar vectors, in TETRA_EDGES order. */
export function tetrahedronMirrors(pts: IdealTetrahedron): CVec3[] {
  return TETRA_EDGES.map(([i, j]) => polarVector(pts[i], pts[j]));
}

/** The 6 edge reflections, in TETRA_EDGES order. */
export function tetrahedronReflections(pts: IdealTetrahedron): CMat[] {
  return tetrahedronMirrors(pts).map((c) => complexReflection(c));
}

/** GroupAction of the full tetrahedron group ⟨ι_{ij}⟩ (6 involutions). */
export function tetrahedronAction(pts: IdealTetrahedron): GroupAction {
  return makeComplexMatrixAction(asComplexInvolutions(tetrahedronReflections(pts)));
}

/** Seed on the limit set. The shortest loxodromic word is generically an
 *  opposite-edge product like ι₁₂ι₃₄ (adjacent-edge products are parabolic). */
export function seedTetrahedron(action: GroupAction): Seed {
  return seedCH2(action, TETRA_EDGE_LABELS);
}

/** Side labels in CYCLIC_SIDES order (p₁p₂, p₂p₃, p₃p₄, p₄p₁). */
export const QUAD_SIDE_LABELS: readonly string[] = ['ι₁₂', 'ι₂₃', 'ι₃₄', 'ι₁₄'];

/** The 4 side reflections of the ideal QUADRILATERAL p₁p₂p₃p₄ (the
 *  CYCLIC_SIDES sub-alphabet of the tetrahedron — diagonals dropped). */
export function quadrilateralReflections(pts: IdealTetrahedron): CMat[] {
  const all = tetrahedronReflections(pts);
  return CYCLIC_SIDES.map((c) => all[c]);
}

/** GroupAction of the ideal quadrilateral group (4 involutions; consecutive
 *  sides share an ideal vertex, opposite sides generically cross or are
 *  ultraparallel — classify them with diagnostics.classifyMirrorPair). */
export function quadrilateralAction(pts: IdealTetrahedron): GroupAction {
  return makeComplexMatrixAction(asComplexInvolutions(quadrilateralReflections(pts)));
}

/** Seed for the quadrilateral sub-alphabet. */
export function seedQuadrilateral(action: GroupAction): Seed {
  return seedCH2(action, QUAD_SIDE_LABELS);
}

/**
 * Lift a Heisenberg point (ζ, v) to a null vector in ball coordinates:
 * Z = ((−|ζ|² + iv)/2, ζ, 1) is J₂-null, and CAYLEY (an involution matching
 * `heisenbergEmbedding`'s conventions exactly) carries it to the ball form.
 * Inverse of the embedding: heisenbergEmbedding(boundaryFromHeisenberg(ζ,v))
 * = (ζ, v), pinned by the gates.
 */
export function boundaryFromHeisenberg(zeta: Cx, v: number): CVec3 {
  const z2 = zeta[0] * zeta[0] + zeta[1] * zeta[1];
  const Z = Float64Array.from([-z2 / 2, v / 2, zeta[0], zeta[1], 1, 0]);
  return cmatVec(CAYLEY, Z);
}

/**
 * The research parameterization of the 4-dim moduli space: base face
 * p₁p₂p₃ = idealTrianglePoints(A), and p₄ from Heisenberg coordinates.
 * (A, ζx, ζy, v) ↔ one tetrahedron per PU(2,1)-orbit, generically.
 */
export function tetrahedronFromModuli(
  A: number, zeta: Cx, v: number,
): IdealTetrahedron {
  const [p1, p2, p3] = idealTrianglePoints(A);
  return [p1, p2, p3, boundaryFromHeisenberg(zeta, v)];
}
